### ISSUE TITLE
(os x lion 10.7.5, Xcode 4.5.1) install issue

### ISSUE THREAD

**Issue by amiltonwong** [bfleischer/fuse_wait#1]
Hi, bflesischer,
    My os x lion version is 10.7.5, and I had installed Xcode 4.5.1(The current version). And I had followed the steps which showed from "https://github.com/osxfuse/osxfuse/wiki/NTFS-3G" and "fuse_wait" section.
   But when I compile it using command:
 ./build.sh . /tmp /

//=======================================
- DIST_DIR=.
- TMP_DIR=/tmp
- ROOT_DIR=/
- PROJNAME=fuse_wait
- DESTDIR=usr/local/bin
- CC=llvm-gcc
- OSX_TARGET=10.7
- SDK=/Developer/SDKs/MacOSX10.7.sdk
- TARGET_FLAGS='-arch i386 -mmacosx-version-min=10.7'
- COMPILE_FLAGS='-arch i386 -mmacosx-version-min=10.7 -isysroot
  /Developer/SDKs/MacOSX10.7.sdk -Wl,-syslibroot,/Developer/SDKs/MacOSX10.7.sdk} -g -Wall -
  fconstant-cfstrings -framework CoreFoundation'
- llvm-gcc -arch i386 -mmacosx-version-min=10.7 -isysroot /Developer/SDKs/MacOSX10.7.sdk '-
  Wl,-syslibroot,/Developer/SDKs/MacOSX10.7.sdk}' -g -Wall -fconstant-cfstrings -framework
  CoreFoundation -o /tmp/fuse_wait ./fuse_wait.c
  ./fuse_wait.c:40:19: error: stdio.h: No such file or directory
  ./fuse_wait.c:41:20: error: unistd.h: No such file or directory
  ./fuse_wait.c:42:36: error: stdlib.h: No such file or directory
  ./fuse_wait.c:43:43: error: CoreFoundation/CoreFoundation.h: No such file or directory
  ./fuse_wait.c:44:32: error: AvailabilityMacros.h: No such file or directory
  ./fuse_wait.c:70: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘mountPath’
  ./fuse_wait.c:80: error: expected ‘)’ before ‘in’
  ./fuse_wait.c: In function ‘PrintDictEntry’:
  ./fuse_wait.c:91: error: ‘NULL’ undeclared (first use in this function)
  ./fuse_wait.c:91: error: (Each undeclared identifier is reported only once
  ./fuse_wait.c:91: error: for each function it appears in.)
  ./fuse_wait.c:92: warning: implicit declaration of function ‘calloc’
  ./fuse_wait.c:92: warning: incompatible implicit declaration of built-in function ‘calloc’
  ./fuse_wait.c:94: warning: implicit declaration of function ‘CFStringGetCString’
  ./fuse_wait.c:94: error: ‘kCFStringEncodingUTF8’ undeclared (first use in this function)
  ./fuse_wait.c:107: warning: implicit declaration of function ‘GetCorruptedMacFUSEStringAsUTF8’
  ./fuse_wait.c:116: warning: implicit declaration of function ‘free’
  ./fuse_wait.c: At top level:
  ./fuse_wait.c:128: error: expected ‘)’ before ‘center’
  ./fuse_wait.c:179: error: expected ‘)’ before ‘*’ token
  ./fuse_wait.c: In function ‘main’:
  ./fuse_wait.c:197: warning: implicit declaration of function ‘PrintUsage’
  ./fuse_wait.c:197: error: ‘stdout’ undeclared (first use in this function)
  ./fuse_wait.c:212: error: ‘CFStringRef’ undeclared (first use in this function)
  ./fuse_wait.c:212: error: expected ‘;’ before ‘timeoutString’
  ./fuse_wait.c:215: warning: implicit declaration of function ‘CFStringGetDoubleValue’
  ./fuse_wait.c:215: error: ‘timeoutString’ undeclared (first use in this function)
  ./fuse_wait.c:216: warning: implicit declaration of function ‘CFRelease’
  ./fuse_wait.c:218: warning: implicit declaration of function ‘fprintf’
  ./fuse_wait.c:218: warning: incompatible implicit declaration of built-in function ‘fprintf’
  ./fuse_wait.c:228: error: ‘CFNotificationCenterRef’ undeclared (first use in this function)
  ./fuse_wait.c:228: error: expected ‘;’ before ‘centerRef’
  ./fuse_wait.c:229: error: expected ‘;’ before ‘notificationObjectName’
  ./fuse_wait.c:230: error: expected ‘;’ before ‘notificationName’
  ./fuse_wait.c:233: error: ‘FALSE’ undeclared (first use in this function)
  ./fuse_wait.c:235: warning: implicit declaration of function ‘NotificationCallback’
  ./fuse_wait.c:235: error: ‘NULL’ undeclared (first use in this function)
  ./fuse_wait.c:235: error: ‘notificationObjectName’ undeclared (first use in this function)
  ./fuse_wait.c:239: error: ‘centerRef’ undeclared (first use in this function)
  ./fuse_wait.c:239: warning: implicit declaration of function
  ‘CFNotificationCenterGetDistributedCenter’
  ./fuse_wait.c:250: warning: implicit declaration of function ‘CFNotificationCenterAddObserver’
  ./fuse_wait.c:250: error: ‘NotificationCallback’ undeclared (first use in this function)
  ./fuse_wait.c:250: error: ‘notificationName’ undeclared (first use in this function)
  ./fuse_wait.c:251: error: ‘CFNotificationSuspensionBehaviorDrop’ undeclared (first use in this
  function)
  ./fuse_wait.c:253: warning: implicit declaration of function ‘fork’
  ./fuse_wait.c:255: warning: incompatible implicit declaration of built-in function ‘fprintf’
  ./fuse_wait.c:255: error: ‘stderr’ undeclared (first use in this function)
  ./fuse_wait.c:264: warning: implicit declaration of function ‘waitpid’
  ./fuse_wait.c:266: warning: implicit declaration of function ‘WIFEXITED’
  ./fuse_wait.c:271: warning: implicit declaration of function ‘WEXITSTATUS’
  ./fuse_wait.c:286: error: expected ‘;’ before ‘mountPathSnapshot’
  ./fuse_wait.c:287: error: ‘mountPathSnapshot’ undeclared (first use in this function)
  ./fuse_wait.c:289: warning: implicit declaration of function ‘CFRunLoopRunInMode’
  ./fuse_wait.c:289: error: ‘kCFRunLoopDefaultMode’ undeclared (first use in this function)
  ./fuse_wait.c:289: error: ‘true’ undeclared (first use in this function)
  ./fuse_wait.c:296: error: ‘mountPath’ undeclared (first use in this function)
  ./fuse_wait.c:298: error: ‘kCFRunLoopRunHandledSource’ undeclared (first use in this function)
  ./fuse_wait.c:299: warning: incompatible implicit declaration of built-in function ‘fprintf’
  ./fuse_wait.c:312: error: ‘CFDataRef’ undeclared (first use in this function)
  ./fuse_wait.c:312: error: expected ‘;’ before ‘utf8Data’
  ./fuse_wait.c:316: error: ‘utf8Data’ undeclared (first use in this function)
  ./fuse_wait.c:320: error: ‘size_t’ undeclared (first use in this function)
  ./fuse_wait.c:320: error: expected ‘;’ before ‘mountPathUTF8Length’
  ./fuse_wait.c:321: warning: incompatible implicit declaration of built-in function ‘calloc’
  ./fuse_wait.c:321: error: ‘mountPathUTF8Length’ undeclared (first use in this function)
  ./fuse_wait.c:322: warning: implicit declaration of function ‘CFDataGetBytes’
  ./fuse_wait.c:322: warning: implicit declaration of function ‘CFRangeMake’
  ./fuse_wait.c:334: warning: implicit declaration of function ‘malloc’
  ./fuse_wait.c:334: warning: incompatible implicit declaration of built-in function ‘malloc’
  ./fuse_wait.c:334: error: ‘PATH_MAX’ undeclared (first use in this function)
  ./fuse_wait.c:336: warning: implicit declaration of function ‘memset’
  ./fuse_wait.c:336: warning: incompatible implicit declaration of built-in function ‘memset’
  ./fuse_wait.c:339: warning: implicit declaration of function ‘realpath’
  ./fuse_wait.c:345: warning: implicit declaration of function ‘strncmp’
  ./fuse_wait.c:388: warning: implicit declaration of function ‘execvp’
  ./fuse_wait.c:389: warning: incompatible implicit declaration of built-in function ‘fprintf’
- exit 1

//=====================================

What's the problem gone wrong?
And I figure out that: " SDK=/Developer/SDKs/MacOSX10.7.sdk    " may be incorrect for my system, because i cannot find /Developer/SDKs/MacOSX10.7.sdk by terminal.

Can you give me some suggestion?

Thanks and regards,
Milton

**Comment by amiltonwong** [comment]
I finally solve that issue by "vi build.sh", modify into the following line:
SDK=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk

And it compiled successfully and NTFS-3G works now ~~

**Comment by bfleischer** [comment]
Fixed! Thanks for the bug report.
