### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by cheekygit** [bfleischer/fuse_wait#2]
I installed FUSE for OS X 2.5.4 and later installed fuse_wait by mistake. I thought I needed it but did not. I never installed NTFS-3G unless it is part of FUSE for OS X 2.5.4. Now one of my USB hard drives is no longer recognized on that computer (it still works on another Mac). I would appreciate instructions for removing fuse_wait 1.1 as I think it might be causally related to my USB problem. Thanks in advance.

**Comment by bfleischer** [comment]
NTFS-3G is not bundled with FUSE for OS X 2.5.4. If you did not install a file system using fuse_wait then fuse_wait cannot be responsible for your USB troubles. It is just a small, passive helper tool.

To remove fuse_wait run the following command in Terminal.

```
sudo rm /usr/local/bin/fuse_wait  
```

**Comment by cheekygit** [comment]
Thanks and you're right. I removed fuse_wait and the USB hard drive still won't show in disk utility. It's the weirdest thing. All my other hard drives are recognized on the same USB port.

**Comment by bfleischer** [comment]
Since fuse_wait does not seem to be causing the issue I'm going to close the ticket.
